name: Deploy Spotifire to GCP

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    environment: GCP
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - id: 'auth'
      name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v0'
      with:
        token_format: access_token
        workload_identity_provider: '${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}'
        service_account: '${{ secrets.SERVICE_ACCOUNT }}'
        access_token_lifetime: '300s'
    - name: Login to Artifact Registry
      uses: docker/login-action@v1
      with:
        registry: us-central1-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}
    - name: Kaniko build
      uses: aevea/action-kaniko@master
      with:
        registry: us-central1-docker.pkg.dev
        image: spfire/spotifire/spotifire
        cache: true
        debug: true
        password: ${{ steps.auth.outputs.access_token }}
    - name: 'Deploy to Cloud Run'
      uses: 'google-github-actions/deploy-cloudrun@v0'
      with:
        image: 'us-central1-docker.pkg.dev/spfire/spotifire/spotifire'
        service: 'spotifire'
        env_vars: 'CLIENT_ID=${{ secrets.CLIENT_ID }},CLIENT_SECRET=${{ secrets.CLIENT_SECRET }},REDIRECT_URI=${{ secrets.REDIRECT_URI }},'
